/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData work = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wc = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_library = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report_problem = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_answer = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart_outlined = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_add = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_outline = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_releases = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monetization_on = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_off = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_box = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_outline = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grade = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_add = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms_failed = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sync_icon = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textsms = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_down = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_up = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_down = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_a_photo = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle_outline = IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_alert = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_shopping_cart = IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_photos = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplanemode_active = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplanemode_inactive = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_add = IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_off = IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData announcement = IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_downward = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_drop_down = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_drop_down_circle = IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_drop_up = IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_upward = IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_forward = IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assessment = IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_file = IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assistant_photo = IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_money = IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attachment = IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData autorenew = IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backspace = IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backup = IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_border = IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData build = IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cached = IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_alt = IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_bubble = IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_bubble_outline = IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_box = IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_box_outline_blank = IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_done = IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_download = IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_upload = IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collections = IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collections_bookmark = IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crop_original = IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_forever = IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_sweep = IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData description = IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_hub = IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_bike = IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donut_small = IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donut_large = IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drafts = IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enhanced_encryption = IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData equalizer = IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error_outline = IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData euro_symbol = IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_border = IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback = IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_download = IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_upload = IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
