/// Flutter icons FamilyBudgetIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FamilyBudgetIcons
///      fonts:
///       - asset: fonts/FamilyBudgetIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class FamilyBudgetIcons {
  FamilyBudgetIcons._();

  static const _kFontFam = 'FamilyBudgetIcons';
  static const String? _kFontPkg = null;

  static const IconData briefcase = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ambulance_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData university = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxi_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle_1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ship_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subway_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle_1 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weekend = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pump_soap = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healing = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_shirt = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscriptions = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shirt = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grade = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_martini = IconData(0xf000, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xf001, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData film = IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData road = IconData(0xf018, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_1 = IconData(0xf06b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane = IconData(0xf072, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xf07a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xf091, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xf09d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase_1 = IconData(0xf0b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask = IconData(0xf0c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_1 = IconData(0xf0d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella = IconData(0xf0e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_md = IconData(0xf0f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suitcase = IconData(0xf0f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xf0f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ambulance = IconData(0xf0f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medkit = IconData(0xf0fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fighter_jet = IconData(0xf0fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer = IconData(0xf0fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepad = IconData(0xf11b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData euro = IconData(0xf153, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xf155, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rouble = IconData(0xf158, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xf19c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_cap = IconData(0xf19d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building_filled = IconData(0xf1ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child = IconData(0xf1ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw = IconData(0xf1b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cab = IconData(0xf1b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxi = IconData(0xf1ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData binoculars = IconData(0xf1e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator = IconData(0xf1ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthday = IconData(0xf1fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_area = IconData(0xf1fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_line = IconData(0xf201, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle = IconData(0xf206, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = IconData(0xf207, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ship = IconData(0xf21a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_secret = IconData(0xf21b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xf21c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = IconData(0xf238, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subway = IconData(0xf239, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData industry = IconData(0xf275, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handshake = IconData(0xf2b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData server = IconData(0xf391, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gem = IconData(0xf3a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xf3bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_alt = IconData(0xf3d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipping_fast = IconData(0xf48b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piggy_bank = IconData(0xf4d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_moving = IconData(0xf4df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData church = IconData(0xf51d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crow = IconData(0xf520, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice = IconData(0xf522, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gas_pump = IconData(0xf52f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helicopter = IconData(0xf533, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_wave = IconData(0xf53a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_wave_alt = IconData(0xf53b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_check = IconData(0xf53c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xf549, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xf54e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_alt = IconData(0xf54f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolbox = IconData(0xf552, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tshirt = IconData(0xf553, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xf555, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = IconData(0xf559, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_alt = IconData(0xf55e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drum = IconData(0xf569, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish = IconData(0xf578, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuttle_van = IconData(0xf5b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimmer = IconData(0xf5c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella_beach = IconData(0xf5ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_hanging = IconData(0xf5cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wine_glass_alt = IconData(0xf5ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brain = IconData(0xf5dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_crash = IconData(0xf5e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData charging_station = IconData(0xf5e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oil_can = IconData(0xf613, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theater_masks = IconData(0xf630, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData socks = IconData(0xf696, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campground = IconData(0xf6bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat = IconData(0xf6be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog = IconData(0xf6d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hammer = IconData(0xf6e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData running = IconData(0xf70c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tractor = IconData(0xf722, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby = IconData(0xf77c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby_carriage = IconData(0xf77d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_cheers = IconData(0xf79f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guitar = IconData(0xf7a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horse_head = IconData(0xf7ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_cream = IconData(0xf810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza_slice = IconData(0xf818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biking = IconData(0xf84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
