name: family_budget
description: Приложение "Семейный бюджет"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  email_validator: ^2.0.1
  sqflite: ^2.0.2
  sqfentity: ^2.2.0+1.pre
  sqfentity_gen: ^2.2.0+2.pre
  build_runner: ^2.1.7
  http: ^0.13.4
  build_verify: ^3.0.0
  collection: ^1.15.0
  image_picker: ^0.7.2+1
  flutter_hooks: ^0.18.2+1
  async: ^2.8.2
  math_expressions: ^2.3.0
  charts_flutter: ^0.12.0
  loop_page_view: ^1.1.1
  infinity_page_view: ^1.0.0
  grouped_list: ^4.2.0
  flutter_launcher_icons: ^0.9.2
  get: ^4.6.5
  socket_io_client: ^1.0.2
  signalr_netcore: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

assets:
  - google_fonts/

flutter_icons:
  android: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "#ffffffff"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:

  generate: false
  uses-material-design: true

  fonts:
    - family: FamilyBudgetIcons
      fonts:
      - asset: fonts/FamilyBudgetIcons.ttf

  assets:
    - assets/images/
