// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:UserParam.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// UserParam TABLE
class TableUserParam extends SqfEntityTableBase {
  TableUserParam() {
    // declare properties of EntityTable
    tableName = 'userParams';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('status', DbType.integer,
          defaultValue: 1, isNotNull: true),
      SqfEntityFieldBase('date_modify', DbType.integer, isNotNull: true),
      SqfEntityFieldBase('logged', DbType.bool,
          defaultValue: false, isNotNull: true),
      SqfEntityFieldBase('name', DbType.text, isNotNull: true),
      SqfEntityFieldBase('mail', DbType.text),
      SqfEntityFieldBase('auth_code', DbType.text),
      SqfEntityFieldBase('avatar', DbType.blob, isNotNull: true),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableUserParam();
  }
}
// END TABLES

// BEGIN DATABASE MODEL
class FamilyBudgetModel extends SqfEntityModelProvider {
  FamilyBudgetModel() {
    databaseName = familyBudgetModel.databaseName;
    password = familyBudgetModel.password;
    dbVersion = familyBudgetModel.dbVersion;
    preSaveAction = familyBudgetModel.preSaveAction;
    logFunction = familyBudgetModel.logFunction;
    databaseTables = [
      TableUserParam.getInstance,
    ];

    bundledDatabasePath = familyBudgetModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region UserParam
class UserParam extends TableBase {
  UserParam(
      {this.id,
      this.status,
      this.date_modify,
      this.logged,
      this.name,
      this.mail,
      this.auth_code,
      this.avatar}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  UserParam.withFields(this.status, this.date_modify, this.logged, this.name,
      this.mail, this.auth_code, this.avatar) {
    _setDefaultValues();
  }
  UserParam.withId(this.id, this.status, this.date_modify, this.logged,
      this.name, this.mail, this.auth_code, this.avatar) {
    _setDefaultValues();
  }
  // fromMap v2.0
  UserParam.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['status'] != null) {
      status = int.tryParse(o['status'].toString());
    }
    if (o['date_modify'] != null) {
      date_modify = int.tryParse(o['date_modify'].toString());
    }
    if (o['logged'] != null) {
      logged =
          o['logged'].toString() == '1' || o['logged'].toString() == 'true';
    }
    if (o['name'] != null) {
      name = o['name'].toString();
    }
    if (o['mail'] != null) {
      mail = o['mail'].toString();
    }
    if (o['auth_code'] != null) {
      auth_code = o['auth_code'].toString();
    }
    if (o['avatar'] != null) {
      avatar = o['avatar'] as Uint8List;
    }
  }
  // FIELDS (UserParam)
  int? id;
  int? status;
  int? date_modify;
  bool? logged;
  String? name;
  String? mail;
  String? auth_code;
  Uint8List? avatar;

  // end FIELDS (UserParam)

  static const bool _softDeleteActivated = false;
  UserParamManager? __mnUserParam;

  UserParamManager get _mnUserParam {
    return __mnUserParam = __mnUserParam ?? UserParamManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (status != null || !forView) {
      map['status'] = status;
    }
    if (date_modify != null || !forView) {
      map['date_modify'] = date_modify;
    }
    if (logged != null) {
      map['logged'] = forQuery ? (logged! ? 1 : 0) : logged;
    } else if (logged != null || !forView) {
      map['logged'] = null;
    }
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (mail != null || !forView) {
      map['mail'] = mail;
    }
    if (auth_code != null || !forView) {
      map['auth_code'] = auth_code;
    }
    if (avatar != null || !forView) {
      map['avatar'] = avatar;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (status != null || !forView) {
      map['status'] = status;
    }
    if (date_modify != null || !forView) {
      map['date_modify'] = date_modify;
    }
    if (logged != null) {
      map['logged'] = forQuery ? (logged! ? 1 : 0) : logged;
    } else if (logged != null || !forView) {
      map['logged'] = null;
    }
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (mail != null || !forView) {
      map['mail'] = mail;
    }
    if (auth_code != null || !forView) {
      map['auth_code'] = auth_code;
    }
    if (avatar != null || !forView) {
      map['avatar'] = avatar;
    }

    return map;
  }

  /// This method returns Json String [UserParam]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [UserParam]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [status, date_modify, logged, name, mail, auth_code, avatar];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [id, status, date_modify, logged, name, mail, auth_code, avatar];
  }

  static Future<List<UserParam>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR UserParam.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<UserParam>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <UserParam>[];
    try {
      objList = list
          .map((userparam) =>
              UserParam.fromMap(userparam as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR UserParam.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<UserParam>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<UserParam> objList = <UserParam>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = UserParam.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns UserParam by ID if exist, otherwise returns null
  /// Primary Keys: int? id
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [UserParam] if exist, otherwise returns null
  Future<UserParam?> getById(int? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    UserParam? obj;
    final data = await _mnUserParam.getById([id]);
    if (data.length != 0) {
      obj = UserParam.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (UserParam) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnUserParam.insert(this, ignoreBatch);
    } else {
      await _mnUserParam.update(this);
    }

    return id;
  }

  /// Saves the (UserParam) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnUserParam.insertOrThrow(this, ignoreBatch);

      isInsert = true;
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnUserParam.updateOrThrow(this);
    }

    return id;
  }

  /// saveAs UserParam. Returns a new Primary Key value of UserParam

  /// <returns>Returns a new Primary Key value of UserParam
  @override
  Future<int?> saveAs({bool ignoreBatch = true}) async {
    id = null;

    return save(ignoreBatch: ignoreBatch);
  }

  void rollbackId() {
    if (isInsert == true) {
      id = null;
    }
  }

  /// saveAll method saves the sent List<UserParam> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<UserParam> userparams) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await FamilyBudgetModel().batchStart();
    for (final obj in userparams) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await FamilyBudgetModel().batchCommit();
      for (int i = 0; i < userparams.length; i++) {
        if (userparams[i].id == null) {
          userparams[i].id = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns id
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnUserParam.rawInsert(
          'INSERT OR REPLACE INTO userParams (id, status, date_modify, logged, name, mail, auth_code, avatar)  VALUES (?,?,?,?,?,?,?,?)',
          [id, status, date_modify, logged, name, mail, auth_code, avatar],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'UserParam id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'UserParam id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'UserParam Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<UserParam>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<UserParam> userparams) async {
    final results = await _mnUserParam.rawInsertAll(
        'INSERT OR REPLACE INTO userParams (id, status, date_modify, logged, name, mail, auth_code, avatar)  VALUES (?,?,?,?,?,?,?,?)',
        userparams);
    return results;
  }

  /// Deletes UserParam

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete UserParam invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnUserParam
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnUserParam.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [UserParam] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  UserParamFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return UserParamFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  UserParamFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return UserParamFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    status = status ?? 1;
    logged = logged ?? false;
  }
  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion userparam

// region UserParamField
class UserParamField extends FilterBase {
  UserParamField(UserParamFilterBuilder userparamFB) : super(userparamFB);

  @override
  UserParamFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder isNull() {
    return super.isNull() as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as UserParamFilterBuilder;
  }

  @override
  UserParamFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as UserParamFilterBuilder;
  }

  @override
  UserParamField get not {
    return super.not as UserParamField;
  }
}
// endregion UserParamField

// region UserParamFilterBuilder
class UserParamFilterBuilder extends ConjunctionBase {
  UserParamFilterBuilder(UserParam obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnUserParam = obj._mnUserParam;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  UserParamManager? _mnUserParam;

  /// put the sql keyword 'AND'
  @override
  UserParamFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  UserParamFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  UserParamFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  UserParamFilterBuilder where(String? whereCriteria,
      {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  UserParamFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  UserParamFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  UserParamFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  UserParamFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  UserParamFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  UserParamFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  UserParamFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  UserParamField _setField(
      UserParamField? field, String colName, DbType dbtype) {
    return UserParamField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  UserParamField? _id;
  UserParamField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  UserParamField? _status;
  UserParamField get status {
    return _status = _setField(_status, 'status', DbType.integer);
  }

  UserParamField? _date_modify;
  UserParamField get date_modify {
    return _date_modify =
        _setField(_date_modify, 'date_modify', DbType.integer);
  }

  UserParamField? _logged;
  UserParamField get logged {
    return _logged = _setField(_logged, 'logged', DbType.bool);
  }

  UserParamField? _name;
  UserParamField get name {
    return _name = _setField(_name, 'name', DbType.text);
  }

  UserParamField? _mail;
  UserParamField get mail {
    return _mail = _setField(_mail, 'mail', DbType.text);
  }

  UserParamField? _auth_code;
  UserParamField get auth_code {
    return _auth_code = _setField(_auth_code, 'auth_code', DbType.text);
  }

  UserParamField? _avatar;
  UserParamField get avatar {
    return _avatar = _setField(_avatar, 'avatar', DbType.blob);
  }

  /// Deletes List<UserParam> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnUserParam!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnUserParam!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from userParams ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnUserParam!.updateBatch(qparams, values);
  }

  /// This method always returns [UserParam] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> UserParam?
  @override
  Future<UserParam?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnUserParam!.toList(qparams);
    final data = await objFuture;
    UserParam? obj;
    if (data.isNotEmpty) {
      obj = UserParam.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [UserParam]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> UserParam?
  @override
  Future<UserParam> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        UserParam();
  }

  /// This method returns int. [UserParam]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? userparamCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final userparamsFuture = await _mnUserParam!.toList(qparams);
    final int count = userparamsFuture[0]['CNT'] as int;
    if (userparamCount != null) {
      userparamCount(count);
    }
    return count;
  }

  /// This method returns List<UserParam> [UserParam]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<UserParam>
  @override
  Future<List<UserParam>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<UserParam> userparamsData = await UserParam.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return userparamsData;
  }

  /// This method returns Json String [UserParam]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [UserParam]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [UserParam]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnUserParam!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [UserParam]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM userParams WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _mnUserParam!.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [UserParam]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnUserParam!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await UserParam.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnUserParam!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion UserParamFilterBuilder

// region UserParamFields
class UserParamFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fStatus;
  static TableField get status {
    return _fStatus =
        _fStatus ?? SqlSyntax.setField(_fStatus, 'status', DbType.integer);
  }

  static TableField? _fDate_modify;
  static TableField get date_modify {
    return _fDate_modify = _fDate_modify ??
        SqlSyntax.setField(_fDate_modify, 'date_modify', DbType.integer);
  }

  static TableField? _fLogged;
  static TableField get logged {
    return _fLogged =
        _fLogged ?? SqlSyntax.setField(_fLogged, 'logged', DbType.bool);
  }

  static TableField? _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }

  static TableField? _fMail;
  static TableField get mail {
    return _fMail = _fMail ?? SqlSyntax.setField(_fMail, 'mail', DbType.text);
  }

  static TableField? _fAuth_code;
  static TableField get auth_code {
    return _fAuth_code = _fAuth_code ??
        SqlSyntax.setField(_fAuth_code, 'auth_code', DbType.text);
  }

  static TableField? _fAvatar;
  static TableField get avatar {
    return _fAvatar =
        _fAvatar ?? SqlSyntax.setField(_fAvatar, 'avatar', DbType.blob);
  }
}
// endregion UserParamFields

//region UserParamManager
class UserParamManager extends SqfEntityProvider {
  UserParamManager()
      : super(FamilyBudgetModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'userParams';
  static const List<String> _primaryKeyList = ['id'];
  static const String _whereStr = 'id=?';
}

//endregion UserParamManager
class FamilyBudgetModelSequenceManager extends SqfEntityProvider {
  FamilyBudgetModelSequenceManager() : super(FamilyBudgetModel());
}
// END OF ENTITIES
